---
# Elasticsearch and others dependencies

- name: Dependencies RedHat
  include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Dependencies Debian
  include: debian.yml
  when: ansible_os_family == 'Debian'

# Skydive installation
- name: Install from sources
  include: from_sources.yml
  when: from_sources == 'yes'

- name: Install from binary only
  include: from_binary.yml
  when: from_sources != 'yes'

# Skydive service

- name: Skydive service - Create conf directory
  file:
    path: "/etc/skydive"
    state: directory

- name: Skydive service - Include vars
  include_vars: "{{ sd_service_type }}.yml"

- name: Skydive service - Create conf file
  template:
    src: skydive.yml.j2
    dest: "/etc/skydive/skydive-{{ sd_service_type }}.yml"

- name: Skydive service - Create var file
  template:
    src: skydive.j2
    dest: "/etc/sysconfig/skydive-{{ sd_service_type }}"

- name: Skydive service - Create systemd unit file
  template:
    src: skydive.service.j2
    dest: "/etc/systemd/system/skydive-{{ sd_service_type }}.service"

- name: Skydive service - Enable and start service
  service:
    name: "skydive-{{ sd_service_type }}"
    enabled: yes
    state: started
