---
- name: Elasticsearch - Import GPG key
  rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Elasticsearch - Repofile
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/

- name: Install dependencies
  yum:
    state: present
    update_cache: yes
    name: "{{ item }}"
  with_items:
    - elasticsearch
    - libpcap-devel
    - git
    - java-1.8.0-openjdk
    - gcc

- name: Start elasticsearch service
  service:
    enabled: yes
    state: started
    name: elasticsearch
